name: Localize AI
description: "Localize your project with GPT"
branding:
  icon: aperture
  color: yellow
inputs:
  openai-token:
    description: 'Openai API token'
    required: true
  locales-path:
    description: 'Path to locales folder'
    default: './locales'
  main-locale:
    description: 'Main locale'
    default: 'en'
  model:
    description: 'GPT model'
    default: 'gpt-4'
  verbose:
    description: 'Verbose mode'
    default: 'false'

runs:
    using: node16
    main: dist/index.js
